- name: Update apt cache
  apt:
    update_cache: yes
  become: yes

- name: Enable Telegraf
  service:
    name: telegraf
    state: started
    enabled: yes
  become: yes

- name: Restart Telegraf
  service:
    name: telegraf
    state: restarted
  become: yes
